pipelines:
  default:
    - step:
        name: fetch code
        script:
          - git submodule update --init
        artifacts:
          - pswgcommon/**
          - client-holocore/**
    - step:
        name: build
        image: openjdk:11-jdk-slim
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew classes testClasses
        artifacts:
          - pswgcommon/**
          - client-holocore/**
          - .gradle/**
          - build/**
    - step:
        name: test
        image: openjdk:11-jdk-slim
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew test
        artifacts:
          - pswgcommon/**
          - client-holocore/**
          - .gradle/**
          - build/**

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper

