pipelines:
  default:
    - step:
        name: test, build, and deploy
        image: openjdk:12
        caches:
          - docker
          - gradle
          - gradlewrapper
        script:
          - git submodule update --init
          - ./gradlew test
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t $DOCKER_HUB_REPO/holocore:$DOCKER_HUB_TAG .
          - docker push $DOCKER_HUB_REPO/holocore:$DOCKER_HUB_TAG
        artifacts:
          - pswgcommon/**
          - client-holocore/**
          - .gradle/**
          - build/**
        services:
          - docker

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper

