name: Deploy to QA

on:
  release:
    types: [published]
    branches:
      - quality_assurance

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build
      run: ./gradlew --no-daemon clean jlink
    - name: Docker Login
      run: docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
    - name: Docker Build
      run: |
        IMAGE_NAME=`echo "docker.pkg.github.com/${GITHUB_REPOSITORY,,}/holocore"`
        RELEASE_NAME=`echo "refs/tags/OCT19-rc1" | sed 's/refs\/tags\///g'`
        docker build -t "$IMAGE_NAME:$RELEASE_NAME" .
        docker tag "$IMAGE_NAME:$RELEASE_NAME" "$IMAGE_NAME:quality_assurance"
    - name: Docker Push
      run: |
        docker push "$IMAGE_NAME:$RELEASE_NAME"
        docker push "$IMAGE_NAME:quality_assurance"
